stages:
  prepare:
    cmd: python -m nuclei_segmentation.data.preprocessing
    deps:
      - data/raw
      - src/nuclei_segmentation/data/preprocessing.py
    params:
      - configs/preprocessing.yaml
    outs:
      - data/processed
  
  train_baseline:
    cmd: python scripts/run_baseline.py
    deps:
      - data/processed
      - src/nuclei_segmentation/models/unet/vanilla_unet.py
      - scripts/run_baseline.py
    params:
      - configs/config.yaml
    metrics:
      - metrics/${model_name}_${mask_type}_metrics.json:
          cache: false
    outs:
      - models/checkpoints/${model_name}