name: nuclei-seg
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - numpy
  - pandas
  - scipy
  - scikit-image
  - scikit-learn
  - matplotlib
  - seaborn
  - wandb
  - opencv
  - albumentations
  - dvc
  - pip
  - pip:
    - lightning  # structured training
    - hydra-core  # configuration management